"""Storage for generated files, plus signed, expiring download links.

Tools save a file and hand the client a link; the link always points at this
server (`GET /files/{id}?expires=...&sig=...`, served by `FileRoutes`), whatever the
backend. The route checks the signature, then streams the file (local) or
redirects to a short-lived storage URL (S3), so on S3 the bucket serves the bytes.

	file = await files.save(pdf_bytes, filename="report.pdf")
	return files.resource_link(file)
"""

import base64
import hashlib
import hmac
import json
import mimetypes
import re
import secrets
import time
import unicodedata
import uuid
from abc import ABC, abstractmethod
from dataclasses import asdict, dataclass
from functools import partial
from typing import Any
from urllib.parse import quote, urlencode

import anyio
import anyio.to_thread
from mcp.types import ResourceLink
from starlette.responses import FileResponse, RedirectResponse, Response

from app.core.logging import get_logger
from app.core.middleware import request_base_url
from app.core.settings import Environment, Settings

FILES_PREFIX = "/files"

# Served content is generated by tools (and often by the model), so never let a browser
# render it inline on this origin.
DOWNLOAD_HEADERS = {"X-Content-Type-Options": "nosniff", "Cache-Control": "private, no-store"}

_FILE_ID = re.compile(r"^[0-9a-f]{32}$")

log = get_logger("app.files")


@dataclass(frozen=True, slots=True)
class StoredFile:
	id: str
	filename: str
	content_type: str
	size: int


class LinkSigner:
	"""
	Signs and verifies download links with HMAC-SHA256 over the file id and expiry time.

	:param key: Secret key shared by every replica that serves links.
	:type key: bytes
	"""

	def __init__(self, key: bytes) -> None:
		self._key = key

	def sign(self, file_id: str, expires: int) -> str:
		mac = hmac.new(self._key, f"{file_id}:{expires}".encode(), hashlib.sha256).digest()
		return base64.urlsafe_b64encode(mac).rstrip(b"=").decode()

	def verify(self, file_id: str, expires: int, sig: str) -> bool:
		if expires < time.time():
			return False
		return hmac.compare_digest(self.sign(file_id, expires), sig)


class FileStore(ABC):
	"""
	Saves generated files and builds signed download links for them.

	Construct with :meth:`from_settings`, and pass the same instance to the toolsets that
	create files and to ``FileRoutes``, which serves them.

	:param settings: Application settings; ``settings.files`` configures the store.
	:type settings: Settings
	:param signer: Signs and verifies download links.
	:type signer: LinkSigner
	"""

	backend: str

	def __init__(self, settings: Settings, signer: LinkSigner) -> None:
		self.settings = settings
		self.config = settings.files
		self.signer = signer

	@classmethod
	def from_settings(cls, settings: Settings) -> FileStore:
		"""
		Creates the store for ``settings.files.backend``.

		:param settings: Application settings.
		:type settings: Settings
		:return: A local or S3 file store.
		:rtype: FileStore
		:raises ValueError: If no signing key is set outside development/test.
		"""
		config = settings.files
		if config.signing_key:
			key = config.signing_key.get_secret_value().encode()
		elif settings.environment in (Environment.DEVELOPMENT, Environment.TEST):
			key = secrets.token_bytes(32)
			log.warning("files.ephemeral_signing_key", detail="links stop working on restart; set files.signing_key")
		else:
			raise ValueError("files.signing_key must be set outside development/test")

		signer = LinkSigner(key)
		if config.backend == "s3":
			return S3FileStore(settings, signer)
		if settings.is_production:
			log.warning("files.local_backend", detail="local files are lost on redeploy and not shared across replicas")
		return LocalFileStore(settings, signer)

	async def save(self, content: bytes | str, filename: str, content_type: str | None = None) -> StoredFile:
		"""
		Stores a file and returns its record.

		:param content: File body; ``str`` is encoded as UTF-8.
		:type content: bytes | str
		:param filename: Name the user's browser saves the file as. Path parts are stripped.
		:type filename: str
		:param content_type: MIME type; guessed from the filename when omitted.
		:type content_type: str | None
		:return: The stored file.
		:rtype: StoredFile
		"""
		data = content.encode() if isinstance(content, str) else content
		filename = _safe_filename(filename)
		if content_type is None:
			content_type = mimetypes.guess_type(filename)[0] or "application/octet-stream"
		file = StoredFile(id=uuid.uuid4().hex, filename=filename, content_type=content_type, size=len(data))
		await self._write(file, data)
		log.info("file.saved", file_id=file.id, filename=file.filename, size=file.size, backend=self.backend)
		return file

	def download_url(self, file: StoredFile) -> str:
		"""
		Builds a signed download link that expires after ``files.link_ttl_seconds``.

		The origin is ``files.public_base_url`` when set, otherwise that of the request being
		handled (API or MCP). Outside a request the link is a relative path.

		:param file: The stored file.
		:type file: StoredFile
		:return: The download URL.
		:rtype: str
		"""
		expires = int(time.time()) + self.config.link_ttl_seconds
		query = urlencode({"expires": expires, "sig": self.signer.sign(file.id, expires)})
		return f"{self._base_url()}{FILES_PREFIX}/{file.id}?{query}"

	def resource_link(self, file: StoredFile, description: str | None = None) -> ResourceLink:
		"""
		Wraps a download link as MCP ``resource_link`` content, for returning from a tool.

		:param file: The stored file.
		:type file: StoredFile
		:param description: Shown to the model/user; defaults to the link's lifetime.
		:type description: str | None
		:return: Content a tool can return directly.
		:rtype: ResourceLink
		"""
		minutes = self.config.link_ttl_seconds // 60
		return ResourceLink(
			type="resource_link",
			uri=self.download_url(file),
			name=file.filename,
			mime_type=file.content_type,
			size=file.size,
			description=description or f"Download link for {file.filename}; expires in {minutes} minutes.",
		)

	def verify(self, file_id: str, expires: int, sig: str) -> bool:
		return bool(_FILE_ID.match(file_id)) and self.signer.verify(file_id, expires, sig)

	async def download_response(self, file_id: str) -> Response | None:
		"""
		Returns the response that delivers the file, or ``None`` if it doesn't exist.

		:param file_id: Id from a link that has already passed :meth:`verify`.
		:type file_id: str
		:rtype: Response | None
		"""
		if not _FILE_ID.match(file_id):
			return None
		return await self._download_response(file_id)

	def _base_url(self) -> str:
		if self.config.public_base_url:
			return self.config.public_base_url.rstrip("/")
		return request_base_url()

	@abstractmethod
	async def _write(self, file: StoredFile, data: bytes) -> None: ...

	@abstractmethod
	async def _download_response(self, file_id: str) -> Response | None: ...


class LocalFileStore(FileStore):
	"""Files on local disk under ``files.local_dir``: the body plus a JSON metadata sidecar."""

	backend = "local"

	def __init__(self, settings: Settings, signer: LinkSigner) -> None:
		super().__init__(settings, signer)
		self.root = self.config.local_dir.resolve()
		self.root.mkdir(parents=True, exist_ok=True)

	async def _write(self, file: StoredFile, data: bytes) -> None:
		await anyio.Path(self.root / file.id).write_bytes(data)
		# Metadata last: its presence marks the file as complete.
		await anyio.Path(self.root / f"{file.id}.json").write_text(json.dumps(asdict(file)))

	async def _download_response(self, file_id: str) -> Response | None:
		meta_path = anyio.Path(self.root / f"{file_id}.json")
		if not await meta_path.exists():
			return None
		file = StoredFile(**json.loads(await meta_path.read_text()))
		return FileResponse(
			self.root / file.id,
			media_type=file.content_type,
			filename=file.filename,
			headers=DOWNLOAD_HEADERS,
		)


class S3FileStore(FileStore):
	"""
	Files in an S3-compatible bucket. Downloads redirect to a short-lived presigned URL.

	:param client: A boto3 S3 client; built from ``settings.files`` when omitted.
	"""

	backend = "s3"

	def __init__(self, settings: Settings, signer: LinkSigner, client: Any = None) -> None:
		super().__init__(settings, signer)
		if client is None:
			import boto3
			from botocore.config import Config

			client = boto3.client(
				"s3",
				region_name=self.config.s3_region,
				endpoint_url=self.config.s3_endpoint_url,
				config=Config(signature_version="s3v4"),
			)
		self.client = client
		self.bucket = self.config.s3_bucket

	def _key(self, file_id: str) -> str:
		return f"{self.config.s3_prefix}{file_id}"

	async def _write(self, file: StoredFile, data: bytes) -> None:
		put = partial(
			self.client.put_object,
			Bucket=self.bucket,
			Key=self._key(file.id),
			Body=data,
			ContentType=file.content_type,
			ContentDisposition=_content_disposition(file.filename),
		)
		await anyio.to_thread.run_sync(put)

	async def _download_response(self, file_id: str) -> Response | None:
		from botocore.exceptions import ClientError

		key = self._key(file_id)
		try:
			await anyio.to_thread.run_sync(partial(self.client.head_object, Bucket=self.bucket, Key=key))
		except ClientError as exc:
			if exc.response.get("Error", {}).get("Code") in ("404", "NoSuchKey", "NotFound"):
				return None
			raise
		url = self.client.generate_presigned_url(
			"get_object",
			Params={"Bucket": self.bucket, "Key": key},
			ExpiresIn=self.config.s3_presign_ttl_seconds,
		)
		return RedirectResponse(url, status_code=302, headers={"Cache-Control": "no-store"})


def _safe_filename(filename: str) -> str:
	name = filename.replace("\\", "/").rsplit("/", 1)[-1]
	name = "".join(ch for ch in name if unicodedata.category(ch)[0] != "C" and ch != '"').strip(" .")
	return name[:200] or "download"


def _content_disposition(filename: str) -> str:
	# RFC 6266: ASCII fallback plus the UTF-8 name for browsers that support it.
	fallback = filename.encode("ascii", "ignore").decode() or "download"
	return f"attachment; filename=\"{fallback}\"; filename*=UTF-8''{quote(filename)}"
